import type { Metadata } from "next";
import { Londrina_Solid, Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/footer";
import Contexts from "./Contexts";

const primaryFont = Londrina_Solid({
  subsets: ["latin"],
  variable: "--primary-font",
  weight: ["100", "300", "400", "900"], // Valores como strings
});
const secondaryFont = Montserrat({
  subsets: ["latin"],
  variable: "--seconday-font",
  weight: ["400", "900"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Contexts>
        <body
          className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}
        >
          <div className="container">
            <NavBar />
            <main className="bleed">{children}</main>
            <Footer />
          </div>
        </body>
      </Contexts>
    </html>
  );
}
